rel["ISO3166-2"="{iso}"]["boundary"="administrative"];
map_to_area;
way["highway"!="motorway"]["highway"!="trunk"]["highway"!="primary_link"]["highway"!="motorway_link"]["highway"!="path"]["highway"!="footway"]["highway"!="pedestrian"]["highway"!="cycleway"]["highway"!="service"]["highway"!="construction"]["highway"!="steps"][!"tramway"][!"railway"][!"proposed"]["route"!="ferry"]["was:route"!="ferry"]["oneway"="yes"](area);
