name: Generate PMTiles

on:
  workflow_dispatch:

jobs:
  generate_pmtiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install tippecanoe
      run: |
        sudo apt-get install gcc g++ make libsqlite3-dev zlib1g-dev
        git clone https://github.com/felt/tippecanoe.git
        cd tippecanoe
        make -j
        sudo make install

    - name: Get GeoJSON from Overpass (w/o France)
      run: python export_oneway_by_country.py

    - name: Get GeoJSON from Overpass (France)
      run: python export_oneway_france.py

    - name: Generate PMTiles from GeoJSONs
      run: | 
        bash oneway_countries/generate_pmtiles.sh
        mv oneway_countries/merged.pmtiles output/

    - name: Minio Deploy
      uses: lovellfelix/minio-deploy-action@v1
      with:
        endpoint: ${{ secrets.MINIO_ENDPOINT }}
        access_key: ${{ secrets.MINIO_ACCESS_KEY }}
        secret_key: ${{ secrets.MINIO_SECRET_KEY }}
        bucket: 'oneway-map'
        source_dir: 'output'
        target_dir: '/'
