name: Generate PMTiles

on:
  workflow_dispatch:

jobs:
  generate_pmtiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install tippecanoe
      run: |
        sudo apt-get install gcc g++ make libsqlite3-dev zlib1g-dev
        git clone https://github.com/felt/tippecanoe.git
        cd tippecanoe
        make -j
        sudo make install
    - name: Install MinIO client mc
      run: |
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        sudo mv mc /usr/local/bin/
        mc --help

    - name: Get GeoJSON from Overpass (w/o France)
      run: python export_oneway.py -r europe.sparql -o oneway_country.overpassql

    - name: Get GeoJSON from Overpass (France)
      run: python export_oneway.py -r france.sparql -o oneway_regions.overpassql

    - name: Generate PMTiles from GeoJSONs
      run: | 
        bash oneway_countries/generate_pmtiles.sh
        mv oneway_countries/merged.pmtiles output/

    - name: Minio Upload
      env:
        MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
        MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
        MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      run: |
        mc alias set deploy "$MINIO_ENDPOINT" "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"
        mc mirror --overwrite output "deploy/oneway-map/"
