name: Generate PMTiles

on:
  workflow_dispatch:

jobs:
  generate_pmtiles:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install tippecanoe
      run: |
        sudo apt-get install gcc g++ make libsqlite3-dev zlib1g-dev
        git clone https://github.com/felt/tippecanoe.git
        cd tippecanoe
        make -j
        sudo make install
