name: Test upload

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
        
    - name: Generate some file
      run: echo "1234" > output/test.txt

    - name: Minio Deploy
      uses: lovellfelix/minio-deploy-action@v1
      with:
        endpoint: ${{ secrets.MINIO_ENDPOINT }}
        access_key: ${{ secrets.MINIO_ACCESS_KEY }}
        secret_key: ${{ secrets.MINIO_SECRET_KEY }}
        bucket: 'oneway-map'
        source_dir: 'output'
        target_dir: '/'
